# -*- coding: utf-8 -*-
"""Ejercicio1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsJmVrRY40maj6AxZcuAp3p17AR7JKdk
"""

#   Codigo que implementa un esquema numerico
#   para determinar la precision de una maquina
#
#           Autor:
#   David Osvaldo Chay May
#   may876518@gmail.com
#   Version 1.0 : 07/02/2025

import numpy as np
import matplotlib.pyplot as plt

epsilon = 1.0
iteracion = 0
epsilons = []## Se creara una lista donde se van a guardar los valores epsilon de cada una de las iteraciones
iteraciones = []## En esta linea se crea un vector y se almacena la iteración correspondiente
while 1.0 + epsilon != 1.0:
    epsilon /= 2
    iteracion = iteracion + 1
    ##Aqui se almacenan los valores de iteracion y epsilon en sus listas respectivas, para luego graficarlos.
    iteraciones.append(iteracion)
    epsilons.append(epsilon)
    print(f"Iteracion: {iteracion}, Precisión de máquina: {epsilon}")

epsilon *= 2
print(f"Precisión de máquina: {epsilon}")

plt.figure()  # Se crea una nueva figura para una grafica
plt.plot(iteraciones, epsilons, label='Epsilon', marker='o')  # Se grafica la evolución de epsilon respecto a las iteraciones, con un marcador en cada punto.
plt.xscale('linear')  # Se define una escala lineal para los ejes X
plt.yscale('linear')  # Se define una escala lineal para el eje y.
#Se añaden etiquetas a los ejes.
plt.xlabel('Iteraciones')
plt.ylabel('Epsilon')
plt.legend()  # Agregue una leyenda a la gráfica.
plt.title('Evolución de la Precisión de Máquina')  # Estableci un título a la gráfica.
plt.show()  # Muestro la gráfica en pantalla.
